server:
  port: 9080

app:
  redisUrl: db.f-li.cn:6379/1
  daemonDelaySeconds: 16
  purgeProcessNames:
    - frpc.exe
    - frps.exe
  daemon:
    frpcFli:
      shell: /cmder_mini/bin/frpc.bat fli-frpc_dns.ini
      successKeywords:
        - login to server success
      failKeywords:
        - try to reconnect to server
      failCountToRestart: 2
    #    frpcFli2:
    #      shell: /cmder_mini/bin/frpc.bat fgo-frpd2.ini
    #      successKeywords:
    #        - login to server success
    #      failKeywords:
    #        - try to reconnect to server
    #      failCountToRestart: 2
    #    frpsYf:
    #      shell: /cmder_mini/bin/frps.bat yf-frps.ini
    #      successKeywords:
    #        - start frps success
    #      failKeywords:
    #      failCountToRestart: 0
    #    frpcYf:
    #      shell: /cmder_mini/bin/frpc.bat yf-frpc.ini
    #      successKeywords:
    #        - login to server successaa
    #      failKeywords:
    #        - try to reconnect to server
    #        - client exit success
    #      failCountToRestart: 0
    frpcFgo:
      shell: /cmder_mini/bin/frpc.bat fgo-frpc.ini
      successKeywords:
        - login to server success
      failKeywords:
        - try to reconnect to server
      failCountToRestart: 3
  jobDelaySeconds: 300
  dnsDb: D:\Desktop\Docker\nginx\coredns\f-li.db
  cronJobs:
    - https://cloud.f-li.cn/cron.php
  sftpEndpoint: jks:123456@mobile.f-li.cn:2222
  python: C:\Users\Youfan-PC\AppData\Local\Programs\Python\Python37\python.exe
  maxExecuteSeconds: 240
  getArgsHost: http://db.f-li.cn:9080
  airtest:
    TRANSFER_FILE:
      workspace: F:\usr\f-li\rx-bot\transferFile.air
      device: android://127.0.0.1:5037/NB4XA6WWS8TGCY4P?cap_method=JAVACAP&&ori_method=MINICAPORI&&touch_method=MINITOUCH
      shell: ${python} -u "F:\usr\f-li\rx-bot\app_launcher.py" "${workspace}" --device "${device}" --log "./log" --argsUrl "${argsUrl}"
    WX_BROADCAST:
      workspace: F:\usr\f-li\rx-bot\wxBroadcast.air
      device: android://127.0.0.1:5037/NB4XA6WWS8TGCY4P?cap_method=JAVACAP&&ori_method=MINICAPORI&&touch_method=MINITOUCH
      shell: ${python} -u "F:\usr\f-li\rx-bot\app_launcher.py" "${workspace}" --device "${device}" --log "./log" --argsUrl "${argsUrl}"
    JD_CLICK:
      workspace: F:\usr\f-li\rx-bot\jdClick.air
      device: android://127.0.0.1:5037/NB4XA6WWS8TGCY4P?cap_method=JAVACAP&&ori_method=MINICAPORI&&touch_method=MINITOUCH
      shell: ${python} -u "F:\usr\f-li\rx-bot\app_launcher.py" "${workspace}" --device "${device}" --log "./log"
    JD_SCAN:
      workspace: F:\usr\f-li\rx-bot\jdScan.air
      device: android://127.0.0.1:5037/NB4XA6WWS8TGCY4P?cap_method=JAVACAP&&ori_method=MINICAPORI&&touch_method=MINITOUCH
      shell: ${python} -u "F:\usr\f-li\rx-bot\app_launcher.py" "${workspace}" --device "${device}" --log "./log"

